== Présentation ==
Ce plugin permet de gérer les cartes Ecodevice de GCE.

Initialement, ce plugin a été créé pour connecter les Ecodevices de GCE.

=== Données visibles sur le Dashboard : ===
* '''les compteurs de Téléinformation '''
* '''les compteurs d'impulsions'''

== Installation/Paramétrage ==
Nous allons maintenant paramétrer un équipement. Pour se faire, cliquer sur '''Plugins / Protocole domotique / Eco-device'''

Puis cliquer sur le bouton en haut à gauche "'''Ajouter un équipement'''"

Puis saisir le nom de l'équipement (ex. Ecodevice 1)

Puis définir :

* '''Objet parent'''
* '''Catégorie '''(optionnelle)
* '''Activer '''(à cocher, sinon l’équipement ne sera pas utilisable)
* '''Visible '''(optionel si vous ne désirez pas le rendre visible sur le Dashboard)
* '''Adresse IP'''
* '''Port'''
* '''Compte'''
* '''Mot de passe'''

== Change log ==

1.9 : Ajout d'une information status

1.8 : Ne pas mettre a jour les données si elles ne changent pas.

1.1 : Problème de ZIP

1.0 : Initialisation